---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-os-redhat
  labels:
    app.kubernetes.io/name: gardener-extension-os-redhat
    helm.sh/chart: gardener-extension-os-redhat
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - operatingsystemconfigs
  - operatingsystemconfigs/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - redhat-leader-election
  verbs:
  - get
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-extension-os-redhat
  labels:
    app.kubernetes.io/name: gardener-extension-os-redhat
    helm.sh/chart: gardener-extension-os-redhat
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-extension-os-redhat
subjects:
- kind: ServiceAccount
  name: gardener-extension-os-redhat
  namespace: {{ .Release.Namespace }}
